# Generated by Django 5.0.4 on 2025-03-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0004_meeting_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='experience',
            new_name='domain',
        ),
    ]
