# Generated by Django 5.0.4 on 2025-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0005_rename_experience_member_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('indisponible', 'Indisponible')], default='disponible', max_length=50),
        ),
    ]
