# Generated by Django 5.0.4 on 2025-03-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0007_area_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmé', 'Confirmé'), ('annulé', 'Annulé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
