# Generated by Django 5.0.4 on 2025-03-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0008_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='message',
            new_name='description',
        ),
        migrations.AddField(
            model_name='folder',
            name='topic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
