# Generated by Django 5.0.4 on 2025-03-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0009_rename_message_folder_description_folder_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
