# Generated by Django 5.0.4 on 2025-03-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0010_remove_folder_date_creation_alter_folder_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='topic',
        ),
    ]
