# Generated by Django 5.0.4 on 2025-03-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0011_remove_contact_message_remove_contact_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
