# Generated by Django 5.0.4 on 2025-03-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0012_alter_contact_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='area',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='area',
            name='tag',
            field=models.CharField(max_length=128, verbose_name='tag'),
        ),
    ]
