# Generated by Django 5.0.4 on 2025-03-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0013_alter_area_description_alter_area_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
    ]
