# Generated by Django 5.1.7 on 2025-04-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0014_alter_area_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
