# Generated by Django 5.1.7 on 2025-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0015_contact_description_alter_contact_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
