# Generated by Django 5.1.7 on 2025-04-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0016_alter_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profession',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
