# Generated by Django 5.1.7 on 2025-04-24 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Law', '0017_contact_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit contenir uniquement des chiffres (8-15 caractères).', regex='^\\d{8,15}$')]),
        ),
    ]
